### ISSUE TITLE
Autocomplete component dependencies

### ISSUE THREAD

**Issue by mbouchenoire** [mbouchenoire/lowfer#10]
Having this scenario :

```yaml
  - name: c1
    type: service
    dependencies:
      - component:
```

The values suggested should be the ones provided by the `/api/components` endpoint (using the architecture as a queryparam).
